# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\GUI\ui_elements\new_ent_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewEnt(object):
    def setupUi(self, NewEnt):
        NewEnt.setObjectName("NewEnt")
        NewEnt.resize(400, 200)
        self.label = QtWidgets.QLabel(NewEnt)
        self.label.setGeometry(QtCore.QRect(9, 9, 201, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(NewEnt)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 201, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(NewEnt)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 201, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(NewEnt)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 160, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(NewEnt)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 201, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(NewEnt)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.errors = QtWidgets.QLabel(NewEnt)
        self.errors.setGeometry(QtCore.QRect(0, 352, 721, 31))
        self.errors.setText("")
        self.errors.setObjectName("errors")

        self.retranslateUi(NewEnt)
        QtCore.QMetaObject.connectSlotsByName(NewEnt)
        NewEnt.setTabOrder(self.lineEdit, self.lineEdit_2)
        NewEnt.setTabOrder(self.lineEdit_2, self.pushButton)
        NewEnt.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, NewEnt):
        _translate = QtCore.QCoreApplication.translate
        NewEnt.setWindowTitle(_translate("NewEnt", "Dialog"))
        self.label.setText(_translate("NewEnt", "TextLabel"))
        self.label_2.setText(_translate("NewEnt", "TextLabel"))
        self.pushButton_2.setText(_translate("NewEnt", "Cancel"))
        self.pushButton.setText(_translate("NewEnt", "Add"))
