# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\GUI\ui_elements\verif.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Verif(object):
    def setupUi(self, Verif):
        Verif.setObjectName("Verif")
        Verif.resize(600, 200)
        self.centralwidget = QtWidgets.QWidget(Verif)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(20, 80, 561, 101))
        self.textBrowser.setObjectName("textBrowser")
        Verif.setCentralWidget(self.centralwidget)

        self.retranslateUi(Verif)
        QtCore.QMetaObject.connectSlotsByName(Verif)

    def retranslateUi(self, Verif):
        _translate = QtCore.QCoreApplication.translate
        Verif.setWindowTitle(_translate("Verif", "Verification"))
        self.label.setText(_translate("Verif", "Verification"))
